//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Teacher
    {
        public int teacherId { get; set; }
        [Required(ErrorMessage ="please Enter Name")]
        [RegularExpression(@"^[A-Za-z ]*$",ErrorMessage ="Alphabet only")]
        public string teacherName { get; set; }
        [Required(ErrorMessage ="Please provide valid Email")]
        public string Email { get; set; }
        [Required]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage ="Date of Joining can't be Empty")]
        public string DateOfJoining { get; set; }
        public string Address { get; set; }

        [Required(ErrorMessage ="Please select Department")]
        public Nullable<int> DeptId { get; set; }
        public string Photo { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
